services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres-pgvector
    ports:
      - "${APP_PG_PORT}:5432"
    environment:
      POSTGRES_USER: ${APP_PG_USER}
      POSTGRES_PASSWORD: ${APP_PG_PASSWORD}
      POSTGRES_DB: ${APP_PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ultimate-advisor-backend
    ports:
      - "8000:8000"
    environment:
      - APP_PG_HOST=db
      - APP_PG_PORT=5432
      - APP_PG_USER=${APP_PG_USER}
      - APP_PG_PASSWORD=${APP_PG_PASSWORD}
      - APP_PG_DATABASE=${APP_PG_DATABASE}
      - APP_ANTHROPIC_API_KEY=${APP_ANTHROPIC_API_KEY}
      - APP_ANTHROPIC_MODEL=${APP_ANTHROPIC_MODEL}
      - APP_VOYAGE_API_KEY=${APP_VOYAGE_API_KEY}
      - APP_VOYAGE_MODEL=${APP_VOYAGE_MODEL}
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
